# Generated by Django 5.2.6 on 2025-11-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=100)),
                ("source_ip", models.CharField(max_length=50)),
                ("port", models.IntegerField()),
                ("protocol", models.CharField(max_length=10)),
                ("action", models.CharField(max_length=10)),
                ("packet_size", models.FloatField()),
                ("duration", models.FloatField()),
                ("login_attempts", models.IntegerField()),
                ("prediction", models.CharField(max_length=20)),
                ("attack_type", models.CharField(max_length=50)),
                ("score", models.FloatField()),
            ],
        ),
    ]
