# Generated by Django 5.2.6 on 2025-11-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityapp", "0004_accesslog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesslog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="ip_address",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="accesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="securefile",
            name="file",
            field=models.FileField(upload_to="secure_files/"),
        ),
    ]
