# securityapp/utils/alerts.py
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()

# securityapp/utils/alerts.py
from django.core.mail import send_mail
from django.conf import settings
import logging

logger = logging.getLogger(__name__)

def send_attack_alert_email(payload: dict):
    """
    Send a concise alert email to the single configured alert recipient.
    The payload may include attacker_username, attacker_ip, file_name, file_id, attack_type, score, notes.
    """
    recipient = getattr(settings, "ALERT_RECIPIENT_EMAIL", None)
    if not recipient:
        logger.warning("ALERT_RECIPIENT_EMAIL not configured in settings. Skipping email send.")
        return

    attacker = payload.get("attacker_username", "unknown")
    attacker_ip = payload.get("attacker_ip", "unknown")
    file_name = payload.get("file_name", "unknown")
    file_id = payload.get("file_id", "N/A")
    attack_type = payload.get("attack_type", "Security Alert")
    score = payload.get("score", "N/A")
    notes = payload.get("notes", "")

    subject = f"🚨 Hybrid Cloud Security — {attack_type}"
    message = (
        f"Alert: {attack_type}\n\n"
        f"File: {file_name} (ID: {file_id})\n"
        f"Attacker: {attacker}\n"
        f"IP: {attacker_ip}\n"
        f"Risk score: {score}\n\n"
        f"Notes: {notes}\n\n"
        f"This alert was generated by the Hybrid Cloud Security system."
    )

    from_email = getattr(settings, "DEFAULT_FROM_EMAIL", "no-reply@hybridcloud.local")

    try:
        send_mail(
            subject,
            message,
            from_email,
            [recipient],
            fail_silently=False,
        )
        logger.info("Alert email sent to %s", recipient)
    except Exception as e:
        # keep a console/log fallback for debugging.
        logger.exception("Failed to send alert email: %s", e)
        # optionally print for dev environment
        if getattr(settings, "DEBUG", False):
            print("Failed to send alert email:", e)
            print("Would have sent to:", recipient)
            print("Message:\n", message)
